language: go
sudo: false
addons:
  hosts:
    - dc1_server

go:
  - "1.10"

script:
  - make docker_build
  - docker-compose -f testdata/docker-compose.yaml up -d srelapd
  - sleep 5
  - cd testdata
  - python -m pip install --user python-ldap
  - env SKIP_TLS=1 python -m unittest -vv test_ldap

deploy:
  - provider: script
    script: make docker_upload
    on:
      branch: master
