language: go
sudo: false
addons:
  hosts:
    - dc1_server
  apt:
    packages:
      - ldap-utils

go:
  - "1.10"

script:
  - make docker_build
  - docker-compose -f testdata/docker-compose.yaml up -d srelapd selapds
  - sleep 5
  - cd testdata
  - env SKIP_TLS=1 python -m unittest -vv test_ldap
  - python -m unittest -vv test_ldap

deploy:
  - provider: script
    script: make docker_upload
    on:
      branch: master
