language: go
sudo: false
addons:
  apt:
    packages:
      - ldap-utils

go:
  - "1.10"

script:
  - make build
  - docker-compose -f build/docker-compose.yaml up srelapd
  - sleep 5
  - ldapsearch -LLL -H ldap://localhost:8089 -D cn=ldap10,ou=sre,dc=tsocial,dc=com -w mysecret -x -bdc=tsocial,dc=com cn=ldap20

deploy:
  - provider: script
    script: make docker_upload
    on:
      branch: master
