language: go

go:
  - "1.10"

script:
  - make docker_build
  - docker-compose -f testdata/docker-compose.yaml up test_ldap
  - docker-compose -f testdata/docker-compose.yaml up test_ldaps

deploy:
  - provider: script
    script: make docker_upload
    on:
      branch: master
